#IHAVECAT API



#######################################################################
############################## HOST ###################################
#######################################################################

###
### local
@domain = http://localhost:3000

### dev
# @domain = https://dev.ihavecat.net

### LIVE
# @domain = https://api.ihavecat.net


#######################################################################
########################### PARAMETER #################################
#######################################################################

###
### 유저
@content = application/json
@user_agent = Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
@access_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJpaGF2ZWNhdC5uZXQiLCJqdGkiOiJoeW9nb2xAbmF2ZXIuY29tIiwiaWF0IjoxNjE4MjQzNDQ3LCJuYmYiOjE2MTgyNDM0NDcsImV4cCI6MTYxODMyOTg0NywiZGF0YSI6eyJpcCI6IjEyNy4wLjAuMSIsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoTGludXg7IEFuZHJvaWQgNy4wOyBTQU1TVU5HIFNNLUc5MzBUIEJ1aWxkL05SRDkwTSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgU2Ftc3VuZ0Jyb3dzZXIvNS4wIENocm9tZS81MS4wLjI3MDQuMTA2IE1vYmlsZSBTYWZhcmkvNTM3LjM2Iiwia2V5IjoiIn19.PAu0TKsKIQ17ZRv-PuIm6almZBNC5PJqFiXyIflbsDY


#######################################################################
############################### API ###################################
#######################################################################

### 로그인
POST {{domain}}/api/v1/users/sign_in.json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "email": "hyogol@naver.com",
  "password": "tt"
}

### 이메일 검증
POST {{domain}}/api/v1/users/validate_email
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "email": "hyogol@naver.com"
}

### 닉네임 검증
POST {{domain}}/api/v1/users/validate_nickname
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "nickname": "hyogol"
}

### 회원가입
POST {{domain}}/api/v1/users.json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "user": {
    "email": "hyogol@naver.com",
    "password": "tt",
    "nickname": "hyogol"
  }
}

### 게시판 리스트
GET {{domain}}/api/v1/boards
Content-Type: {{content}}
User-Agent: {{user_agent}}
access-token: {{access_token}}

### 게시판 상세
GET {{domain}}/api/v1/boards/3
Content-Type: {{content}}
User-Agent: {{user_agent}}
access-token: {{access_token}}

### 게시판 생성
POST {{domain}}/api/v1/boards
Content-Type: {{content}}
User-Agent: {{user_agent}}
access-token: {{access_token}}

{
  "board": {
    "group_id": 3,
    "title": "title",
    "body": "body",
    "tag_list": ["test"]
  }
}










