#IHAVECAT API



#######################################################################
############################## HOST ###################################
#######################################################################

###
### local
@domain = http://localhost:3000

### dev
# @domain = https://dev.ihavecat.net

### LIVE
# @domain = https://ihavecat.net


#######################################################################
########################### PARAMETER #################################
#######################################################################

###
### 도매
@content = application/json
@dome_agent = Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
@dome_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZWFsaS5uZXQiLCJqdGkiOiJwdXNoZG9tZSIsImlhdCI6MTU5NDM3MDkwNywibmJmIjoxNTk0MzcwOTA3LCJleHAiOjE1OTQ0NTczMDcsImRhdGEiOnsidXVpZCI6IjAwMDAwMDAwLTQ0MzMtM2E1NS1mZmZmLWZmZmY5ZmZmZWQ5OSIsImlwIjoiMTI3LjAuMC4xIiwidXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChMaW51eDsgQW5kcm9pZCA3LjA7IFNBTVNVTkcgU00tRzkzMFQgQnVpbGQvTlJEOTBNKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci81LjAgQ2hyb21lLzUxLjAuMjcwNC4xMDYgTW9iaWxlIFNhZmFyaS81MzcuMzYiLCJrZXkiOiIifX0.Ei3sd154PdXWggcz0WhMH4APOJIrTOJ-XFRaAHgziqY

# ###
# ### 소매
@some_agent = Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
@some_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZWFsaS5uZXQiLCJqdGkiOiJjZWJyIiwiaWF0IjoxNjA2NzMzNzc0LCJuYmYiOjE2MDY3MzM3NzQsImV4cCI6MTYwNjgyMDE3NCwicGFydCI6IlIiLCJkYXRhIjp7InV1aWQiOm51bGwsImlwIjoiMTI3LjAuMC4xIiwidXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChMaW51eDsgQW5kcm9pZCA3LjA7IFNBTVNVTkcgU00tRzkzMFQgQnVpbGQvTlJEOTBNKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBTYW1zdW5nQnJvd3Nlci81LjAgQ2hyb21lLzUxLjAuMjcwNC4xMDYgTW9iaWxlIFNhZmFyaS81MzcuMzYiLCJrZXkiOiIifX0.ZaDsOow7ZRovYGI1YpfDsKNmOxP3SLalK2uCYy8TNAE


#######################################################################
############################### API ###################################
#######################################################################

###
# 로그인
POST {{domain}}/api/v1/users/sign_in.json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "email": "hyogol6@naver.com",
  "password": "tt"
}

###
# 이메일 검증
POST {{domain}}/api/v1/users/validate_email
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "email": "hyogol@naver.com"
}

###
# 닉네임 검증
POST {{domain}}/api/v1/users/validate_nickname
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "nickname": "hyogol"
}

###
# 회원가입
POST {{domain}}/api/v1/users.json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/51.0.2704.106 Mobile Safari/537.36
Referer: https://partner.sinsangmarket.kr

{
  "user": {
    "email": "hyogol15@naver.com",
    "password": "tt",
    "nickname": "hyogol15"
  }
}
